# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Reptrack-production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://reptrackproduction.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_10b71a1bee054ee3973164a22effe1c1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_79e570f726d3402ea30d1b4faab32007 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: reptrackproduction.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_10b71a1bee054ee3973164a22effe1c1 }}/reptrack.azurecr.io/reptrackproduction:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Reptrack-production'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_107896d0ec2a4df2818db31da919c55f }}
        images: 'reptrackproduction.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_10b71a1bee054ee3973164a22effe1c1 }}/reptrack.azurecr.io/reptrackproduction:${{ github.sha }}'