# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - reptrackdep

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://reptrackdepp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c6371d0a94784408b5763fb73e697001 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ed6f09e6fe544175bac55b8f9b978315 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: reptrackdepp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c6371d0a94784408b5763fb73e697001 }}/reptrackdep.azurecr.io/rlkkeptrackdep/reptrackdep/v20:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'reptrackdep'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_147e494b5a7d4dbaa881de977c2c3c96 }}
        images: 'reptrackdepp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c6371d0a94784408b5763fb73e697001 }}/reptrackdep.azurecr.io/rlkkeptrackdep/reptrackdep/v20:${{ github.sha }}'